package:
  name: bash-completion
  version: 2.15.0
  epoch: 0
  description: Programmable completion functions for bash
  copyright:
    - license: GPL-2.0-or-later
  dependencies:
    runtime:
      - bash
  scriptlets:
    post-install: |
      #!/bin/bash
      source /etc/bash/bash_completion.sh

environment:
  contents:
    packages:
      - autoconf
      - automake
      - bash
      - build-base
      - busybox
      - make
      - wolfi-baselayout

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/scop/bash-completion
      tag: ${{ package.version }}
      expected-commit: "0543d1a28ce3d36741675c7ef6da7c2286288f3e"

  - runs: |
      autoreconf -i
      ./configure --prefix=/usr \
          --sysconfdir=/etc \
          --mandir=/usr/share/man \
          --localstatedir=/var
      make
      make DESTDIR=${{targets.destdir}} install
      mkdir -p ${{targets.destdir}}/etc/bash
      mv ${{targets.destdir}}/etc/profile.d/bash_completion.sh ${{targets.destdir}}/etc/bash/
      rmdir -p ${{targets.destdir}}/etc/profile.d/ || true
      mkdir -p ${{targets.destdir}}/usr/lib
      mv ${{targets.destdir}}/usr/share/pkgconfig ${{targets.destdir}}/usr/lib/pkgconfig

update:
  enabled: true
  github:
    identifier: scop/bash-completion
