package:
  name: blackfire
  version: 2.28.16
  epoch: 0
  description: "Blackfire CLI"
  copyright:
    - license: PROPRIETARY
  options:
    no-provides: true

environment:
  contents:
    packages:
      - bash
      - busybox
      - curl

pipeline:
  - uses: fetch
    if: ${{build.arch}} == 'x86_64'
    with:
      uri: https://blackfire.io/api/v1/releases/cli/linux/x86_64
      expected-sha512: 6eb406cc0f7b2f60eed484076491a89f808090b3c29333f1059a151aeccaba8b622a86091364e24682fef68216c7856ba1cb71695ff63dabdb1c70c82739fce2

  - uses: fetch
    if: ${{build.arch}} == 'aarch64'
    with:
      uri: https://blackfire.io/api/v1/releases/cli/linux/aarch64
      expected-sha512: 2c70f205126c2ec7bb23fe3ae85274454115e364caf527bc0502ad866fab600362cbc7a3f821739919607a7ac5ecd41fab629ca81122389332f78bf3d6277066

  - runs: |
      tar xfv ${{build.arch}}
      mkdir -p ${{targets.destdir}}/usr/bin
      mv blackfire ${{targets.destdir}}/usr/bin/

update:
  enabled: true
  release-monitor:
    identifier: 372834

test:
  pipeline:
    - runs: |
        blackfire version
