package:
  name: php-frankenphp-8.2-mongodb
  version: 2.1.0
  epoch: 0
  description: "MongoDB driver"
  copyright:
    - license: PHP-3.01
  dependencies:
    runtime:
      - php-frankenphp-8.2

environment:
  contents:
    packages:
      - autoconf
      - automake
      - binutils
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - cyrus-sasl-dev
      - gcc
      - icu-dev
      - libtool
      - openssl-dev>3
      - php-frankenphp-8.2-dev
      - snappy-dev
      - zstd-dev

pipeline:
  - uses: fetch
    with:
      uri: https://pecl.php.net/get/mongodb-${{package.version}}.tgz
      expected-sha512: 0782d1f3544bb748e574d416a1382ee9aa588536a7c965bcf03bb52ec0ddb87968b245d1b8ae917f200bdcb09f1ef3def7841fd37d46143f8c933d3106c385b7

  - name: phpize and configure
    runs: |
      phpize
      ./configure --prefix=/usr --with-php-config=php-config

  - uses: autoconf/make

  - name: Install
    runs: |
      make INSTALL_ROOT="${{targets.destdir}}" install
      install -d ${{targets.destdir}}/etc/php/conf.d
      echo "extension=mongodb.so" > ${{targets.destdir}}/etc/php/conf.d/mongodb.ini

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 11158
