package:
  name: php-frankenphp-8.3-tideways
  version: 5.17.2
  epoch: 0
  description: "Tideways PHP Probe"
  copyright:
    - license: PROPRIETARY
  dependencies:
    runtime:
      - ${{package.name}}-config
      - php-frankenphp-8.3

environment:
  contents:
    packages:
      - busybox
      - wget

pipeline:
  - uses: fetch
    if: ${{build.arch}} == 'x86_64'
    with:
      uri: https://tideways.s3.amazonaws.com/extension/${{package.version}}/tideways-php-${{package.version}}-x86_64.tar.gz
      expected-sha512: 15377378d258909975860c01fa039c9c82bb676c47e4914fdcacef083f50f17c2db0cd02da259b28d2fc10c743b80ba85257f307475494f64509e066b2b5ec6f

  - uses: fetch
    if: ${{build.arch}} == 'aarch64'
    with:
      uri: https://tideways.s3.amazonaws.com/extension/${{package.version}}/tideways-php-${{package.version}}-arm64.tar.gz
      expected-sha512: 1a4f6b26f5cf82714d52b9464f7e7cafb416061fe13826154fd63f352fc7840c76b66d670068c7aea88264802d785056e0be4111bbe286d5638ea4cf27c834c2

  - name: Copy
    runs: |
      mkdir -p ${{targets.destdir}}/usr/lib/php/modules/
      cp tideways-php-8.3-zts.so ${{targets.destdir}}/usr/lib/php/modules/tideways.so

subpackages:
  - name: ${{package.name}}-config
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}/etc/php/conf.d"
          echo "extension=tideways.so" > "${{targets.subpkgdir}}/etc/php/conf.d/tideways.ini"

update:
  enabled: true
  release-monitor:
    identifier: 371870
