package:
  name: php-8.3-blackfire
  version: 1.92.38
  epoch: 0
  description: "Blackfire PHP Probe"
  copyright:
    - license: PROPRIETARY
  dependencies:
    runtime:
      - ${{package.name}}-config
      - php-8.3

environment:
  contents:
    packages:
      - busybox

pipeline:
  - uses: fetch
    if: ${{build.arch}} == 'x86_64'
    with:
      uri: https://packages.blackfire.io/binaries/blackfire-php/${{package.version}}/blackfire-php-linux_amd64-php-83.so
      expected-sha512: 2de884acbe49c76875621579bbe242839843bcb13c66fc557034ce65c758ab3e854a2ac5a483728829dce0ca0a005a5b2bda2f372ab321b0cf1ac36152eec367
      extract: false

  - uses: fetch
    if: ${{build.arch}} == 'aarch64'
    with:
      uri: https://packages.blackfire.io/binaries/blackfire-php/${{package.version}}/blackfire-php-linux_arm64-php-83.so
      expected-sha512: 747f8cb4530bbcf82f2878936f0f773022104bc9ca20eb130552270f44a5d33d94d5e2260417a3950aba146394e450960973c5dec19e3dced6b89fafd6115d03
      extract: false

  - name: Copy
    if: ${{build.arch}} == 'x86_64'
    runs: |
      mkdir -p ${{targets.destdir}}/usr/lib/php/modules/
      cp blackfire-php-linux_amd64-php-83.so ${{targets.destdir}}/usr/lib/php/modules/blackfire.so

  - name: Copy
    if: ${{build.arch}} == 'aarch64'
    runs: |
      mkdir -p ${{targets.destdir}}/usr/lib/php/modules/
      cp blackfire-php-linux_arm64-php-83.so ${{targets.destdir}}/usr/lib/php/modules/blackfire.so

subpackages:
  - name: ${{package.name}}-config
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}/etc/php/conf.d"
          echo "extension=blackfire.so" > "${{targets.subpkgdir}}/etc/php/conf.d/blackfire.ini"

update:
  enabled: true
  release-monitor:
    identifier: 371867
