package:
  name: php-8.2-pcov
  version: 1.0.11
  epoch: 1
  description: "CodeCoverage compatible driver for PHP"
  copyright:
    - license: PHP-3.01
  dependencies:
    runtime:
      - ${{package.name}}-config
      - php-8.2

environment:
  contents:
    packages:
      - autoconf
      - build-base
      - busybox
      - php-8.2
      - php-8.2-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/krakjoe/pcov.git
      tag: v${{package.version}}
      expected-commit: a497e8318801bdc515b468abd15a320c04387c66

  - name: Prepare build
    runs: phpize

  - name: Configure
    runs: ./configure --enable-pcov

  - uses: autoconf/make

  - name: Make install
    runs: INSTALL_ROOT="${{targets.destdir}}" DESTDIR="${{targets.destdir}}" make install

subpackages:
  - name: ${{package.name}}-config
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}/etc/php/conf.d"
          echo "extension=pcov.so" > "${{targets.subpkgdir}}/etc/php/conf.d/pcov.ini"

update:
  enabled: true
  github:
    identifier: krakjoe/pcov
    use-tag: true
    strip-prefix: v
