package:
  name: php-frankenphp-8.4-tideways
  version: 5.17.0
  epoch: 0
  description: "Tideways PHP Probe"
  copyright:
    - license: PROPRIETARY
  dependencies:
    runtime:
      - ${{package.name}}-config
      - php-frankenphp-8.4

environment:
  contents:
    packages:
      - busybox
      - wget

pipeline:
  - uses: fetch
    if: ${{build.arch}} == 'x86_64'
    with:
      uri: https://tideways.s3.amazonaws.com/extension/${{package.version}}/tideways-php-${{package.version}}-x86_64.tar.gz
      expected-sha512: 07277367c9f076d95d709a19dde3187ee5843932c1156e61dc6ff2852c9d6ac3685d1dc29e17b1f7ffa2b6e8be8598a506de98a44afa9fdbb2e6fdef48441abc

  - uses: fetch
    if: ${{build.arch}} == 'aarch64'
    with:
      uri: https://tideways.s3.amazonaws.com/extension/${{package.version}}/tideways-php-${{package.version}}-arm64.tar.gz
      expected-sha512: e33dd1b27bece4ab34196d4ade11a476bf2e84211d214cf06f4ee65c41c1693ff0e64f6577b53b19faca80263e4e24dc8973fb4e8a26f0712d1ed8de524d0f71

  - name: Copy
    runs: |
      mkdir -p ${{targets.destdir}}/usr/lib/php/modules/
      cp tideways-php-8.4-zts.so ${{targets.destdir}}/usr/lib/php/modules/tideways.so

subpackages:
  - name: ${{package.name}}-config
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}/etc/php/conf.d"
          echo "extension=tideways.so" > "${{targets.subpkgdir}}/etc/php/conf.d/tideways.ini"

update:
  enabled: true
  release-monitor:
    identifier: 371870
