package:
  name: php-8.3-nsq
  version: 3.9.0
  epoch: 0
  description: "a php nsq client write by c extension,the fastest nsq client"
  copyright:
    - license: PHP-3.01
  dependencies:
    runtime:
      - php-8.3

environment:
  contents:
    packages:
      - autoconf
      - build-base
      - busybox
      - libevent-dev
      - php-8.3
      - php-8.3-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/yunnian/php-nsq.git
      tag: v${{package.version}}
      expected-commit: 86ad35f956eba371b4eac4998409203bcbbf3cee

  - name: Prepare build
    runs: phpize

  - name: Configure
    runs: ./configure

  - uses: autoconf/make

  - name: Make install
    runs: INSTALL_ROOT="${{targets.destdir}}" DESTDIR="${{targets.destdir}}" make install

  - runs: |
      mkdir -p "${{targets.destdir}}/etc/php/conf.d"
      echo "extension=nsq.so" > "${{targets.destdir}}/etc/php/conf.d/nsq.ini"

update:
  enabled: true
  github:
    identifier: yunnian/php-nsq
    strip-prefix: v
