package:
  name: php-frankenphp-8.3-protobuf
  version: 4.30.1
  epoch: 0
  description: "Protocol Buffers - Google's data interchange format"
  copyright:
    - license: BSD-3-Clause
  dependencies:
    runtime:
      - ${{package.name}}-config
      - php-frankenphp-8.3

environment:
  contents:
    packages:
      - autoconf
      - build-base
      - busybox
      - php-frankenphp-8.3
      - php-frankenphp-8.3-dev
      - protobuf-dev

pipeline:
  - uses: fetch
    with:
      uri: https://pecl.php.net/get/protobuf-${{package.version}}.tgz
      expected-sha512: f54b846c41098b5eba0433232ec40fc9f171975e6949580f4aa84d29297b467ff859550e03b30bebe336588d8903ea152ce1360e278920ff1b3714d1419e7c59

  - name: Prepare build
    runs: phpize

  - name: Build
    runs: ./configure

  - name: Make install
    runs: |
      INSTALL_ROOT="${{targets.destdir}}" DESTDIR="${{targets.destdir}}" make install

subpackages:
  - name: ${{package.name}}-config
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}/etc/php/conf.d"
          echo "extension=protobuf.so" > "${{targets.subpkgdir}}/etc/php/conf.d/protobuf.ini"

update:
  enabled: true
  release-monitor:
    identifier: 141406
