package:
  name: php-8.1-blackfire
  version: 1.92.32
  epoch: 0
  description: "Blackfire PHP Probe"
  copyright:
    - license: PROPRIETARY
  dependencies:
    runtime:
      - ${{package.name}}-config
      - php-8.1

environment:
  contents:
    packages:
      - busybox

pipeline:
  - uses: fetch
    if: ${{build.arch}} == 'x86_64'
    with:
      uri: https://packages.blackfire.io/binaries/blackfire-php/${{package.version}}/blackfire-php-linux_amd64-php-81.so
      expected-sha512: 2364352d3744dd62fffd7f044290ab5b21630868b86af5292de7b2c7bd7449209df69d1ee52489c9bf95eea99b9d4a7ca8affe8c8d5521a5e91a13781d831e0c
      extract: false

  - uses: fetch
    if: ${{build.arch}} == 'aarch64'
    with:
      uri: https://packages.blackfire.io/binaries/blackfire-php/${{package.version}}/blackfire-php-linux_arm64-php-81.so
      expected-sha512: c4fc63b1614e108a6bdc75e790d1dfa9d9f5ce8da951395e2ac6481a3054044592de33d13f0d8af10d2fc5fd7d892eb36e352885dccfd39fae438b03c5c026cf
      extract: false

  - name: Copy
    if: ${{build.arch}} == 'x86_64'
    runs: |
      mkdir -p ${{targets.destdir}}/usr/lib/php/modules/
      cp blackfire-php-linux_amd64-php-81.so ${{targets.destdir}}/usr/lib/php/modules/blackfire.so

  - name: Copy
    if: ${{build.arch}} == 'aarch64'
    runs: |
      mkdir -p ${{targets.destdir}}/usr/lib/php/modules/
      cp blackfire-php-linux_arm64-php-81.so ${{targets.destdir}}/usr/lib/php/modules/blackfire.so

subpackages:
  - name: ${{package.name}}-config
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}/etc/php/conf.d"
          echo "extension=blackfire.so" > "${{targets.subpkgdir}}/etc/php/conf.d/blackfire.ini"

update:
  enabled: true
  release-monitor:
    identifier: 371867
