package:
  name: php-frankenphp-8.4-tideways
  version: 5.18.2
  epoch: 0
  description: "Tideways PHP Probe"
  copyright:
    - license: PROPRIETARY
  dependencies:
    runtime:
      - ${{package.name}}-config
      - php-frankenphp-8.4

environment:
  contents:
    packages:
      - busybox
      - wget

pipeline:
  - uses: fetch
    if: ${{build.arch}} == 'x86_64'
    with:
      uri: https://tideways.s3.amazonaws.com/extension/${{package.version}}/tideways-php-${{package.version}}-x86_64.tar.gz
      expected-sha512: b94c2e13e52be91ebd359689bba0847c6f1559cf3c3ea5e58eeafc9609d82b43956e96e0b8f177b7922e35ff207cedcdec156df1f7cbd27ae836b452cd9fe2cd

  - uses: fetch
    if: ${{build.arch}} == 'aarch64'
    with:
      uri: https://tideways.s3.amazonaws.com/extension/${{package.version}}/tideways-php-${{package.version}}-arm64.tar.gz
      expected-sha512: 6e96ff33e7f100255b4cfdd57365a8d841fd3e0d94221de6294b46e21b9e555aaab815b31844a4d6242d011da8e646de85a6d8aca26f42fe1dd07bd87d316f1c

  - name: Copy
    runs: |
      mkdir -p ${{targets.destdir}}/usr/lib/php/modules/
      cp tideways-php-8.4-zts.so ${{targets.destdir}}/usr/lib/php/modules/tideways.so

subpackages:
  - name: ${{package.name}}-config
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}/etc/php/conf.d"
          echo "extension=tideways.so" > "${{targets.subpkgdir}}/etc/php/conf.d/tideways.ini"

update:
  enabled: true
  release-monitor:
    identifier: 371870
