name: Wolfictl Update From GitHub

on:
  workflow_dispatch:
  # Triggers the workflow every hour
  schedule:
    - cron: "0 * * * *"

permissions:
  contents: read
  id-token: write

env:
  GIT_AUTHOR_NAME: frosh-ci
  GIT_AUTHOR_EMAIL: ci@fos.gg

jobs:
  update:
    name: Wolfictl Update
    if: github.repository == 'shyim/wolfi-php'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

    - uses: octo-sts/action@6177b4481c00308b3839969c3eca88c96a91775f # v1.0.0
      id: octo-sts
      with:
        scope: ${{ github.repository }}
        identity: github-updates

    - uses: docker://quay.io/shyim/wolfi-dev:latest
      env:
          GITHUB_TOKEN: ${{ steps.octo-sts.outputs.token }}
          GIT_AUTHOR_NAME: ${{ env.GIT_AUTHOR_NAME }}
          GIT_AUTHOR_EMAIL: ${{ env.GIT_AUTHOR_EMAIL }}
      with:
        entrypoint: wolfictl
        args: update https://github.com/${{github.repository}} --release-monitoring-query=false --use-gitsign --github-labels=request-version-update --github-labels=automated pr
